version: "3.8"
services:
  api:
    restart: always
    deploy:
      replicas: 2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088-8089:8088"
    environment:
      PORT: 8088

  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80